api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    formats:
        json: ['application/json']
        jsonld: ['application/json+ld']
        html: [ 'text/html' ]
        multipart: [ 'multipart/form-data' ]
    patch_formats:
        json: ['application/json']
    swagger:
        versions: [3]
    eager_loading:
        max_joins: 150
    defaults:
        pagination_enabled: false