gesdinet_jwt_refresh_token:
  user_identity_field: id
  single_use: true
  ttl: 5400
  refresh_token_class: App\Entity\RefreshToken
  user_provider: security.user.provider.concrete.app_user_provider