knp_snappy:
    pdf:
        enabled:    true
        binary:    '%env(WKHTMLTOPDF_PATH)%'
    #    binary:    '%kernel.project_dir%/wkhtmltopdf'
    #    binary:    "%kernel.project_dir%/vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64"
        options:
            enable-local-file-access: true
        env: []
    image:
        enabled:    true
        binary:     "\"%kernel.project_dir%\\public\\wkhtmltopdf\\bin\\wkhtmltopdf.exe\""
        options:    []
