# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration

parameters:
  kernel: "%kernel.project_dir%"
  avatars_directory: "%kernel.project_dir%/public/images/avatars"
  instituts_directory: "%kernel.project_dir%/public/images/instituts"
  bibliotheque_directory: "%kernel.project_dir%/public/files/bibliotheques"
  bulletin_directory: "%kernel.project_dir%/public/files/bulletins"
  passage_directory: "%kernel.project_dir%/public/files/passages"
  certificat_directory: "%kernel.project_dir%/public/files/certificats"
  autorisation_directory: "%kernel.project_dir%/public/files/autorisations"
  sanction_directory: "%kernel.project_dir%/public/files/sanctions"
  facture_directory: "%kernel.project_dir%/public/files/factures"
  base_qrcode: "%env(BASE_QRCODE)%"
  client_url: "%env(CLIENT_URL)%"

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"

  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones
  App\OpenApi\OpenApiFactory:
    decorates: "api_platform.openapi.factory"
    arguments: ['@App\OpenApi\OpenApiFactory.inner']
    autoconfigure: false

  'App\Serializer\UserNormalizer':
    tags:
      - { name: "serializer.normalizer", priority: 64 }
  'App\Serializer\InstitutNormalizer':
    tags:
      - { name: "serializer.normalizer", priority: 64 }
  'App\Serializer\BibliothequeNormalizer':
    tags:
      - { name: "serializer.normalizer", priority: 64 }
  'App\Serializer\SoutenanceNormalizer':
    tags:
      - { name: "serializer.normalizer", priority: 64 }
